### ISSUE TITLE
Orleans 9 Support

### ISSUE THREAD

**Issue by seniorquico** [OrleansContrib/OrleansTestKit#171]
This is a placeholder issue for supporting the newly released Orleans 9.

**Comment by seniorquico** [comment]
@ReubenBond Might the Orleans v8 packages receive ongoing updates (bug fixes?) similar to the v7 and v3 packages? Underlying question- should this project maintain a separate v8 branch to provide backwards compatibility for those that do not yet upgrade to v9? We have kept branches specific to v3 and v4 in this project for this reason. Thanks for any insights you can provide!

**Comment by Badabunga** [comment]
Are there any known Issues regarding the compatibility to Orleans 9 vs the current version of the Test kit ? If so are there any attempts for updating this project to the latest Orleans version ?

**Comment by jkonecki** [comment]
I haven't run into any issues on my project. Testing grains and reminders.

**Comment by Badabunga** [comment]
Ok I could test the functionality over here as well, had no Issues. Thank you for the fast reply, from my perspective this issue can be closed

**Comment by SylvainRollinetSoftcom** [comment]
Any news about this issue? I tried with the latest version and for me it doesn't work

Orleans 8.2.0 -> OK
Orleans > 9.0.0 -> Got an exception in the `TestKitSilo` ctor

```
System.TypeLoadException
Could not load type 'Orleans.Runtime.ICatalog' from assembly 'Orleans.Core, Version=9.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at OrleansCodeGen.OrleansRuntime.Metadata_OrleansRuntime.ConfigureInner(TypeManifestOptions config)
   at Orleans.Serialization.Configuration.TypeManifestProviderBase.Microsoft.Extensions.Options.IConfigureOptions<Orleans.Serialization.Configuration.TypeManifestOptions>.Configure(TypeManifestOptions options) in /_/src/Orleans.Serialization/Configuration/ITypeManifestProvider.cs:line 22
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Orleans.Serialization.TypeSystem.TypeConverter..ctor(IEnumerable`1 formatters, IEnumerable`1 typeNameFilters, IEnumerable`1 typeFilters, IOptions`1 options, TypeResolver typeResolver) in /_/src/Orleans.Serialization/TypeSystem/TypeConverter.cs:line 79
   at InvokeStub_TypeConverter..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.TestKit.TestKitSilo..ctor()
   at Orleans.TestKit.TestKitBase..ctor()
   at Expic.Core.Grains.Tests.OperatingModeGrainTest..ctor(ITestOutputHelper output) in C:\Users\sro\dev\Projects\Mobility\Expic\test\Expic.Core.Grains.Tests\OperatingModeGrainTest.cs:line 25
   at InvokeStub_OperatingModeGrainTest..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
