### ISSUE TITLE
GrainProbeTests.ProbeWithClassPrefix is not testing anything. Fixing it is raising an exception.

### ISSUE THREAD

**Issue by Johanny** [OrleansContrib/OrleansTestKit#65]
While looking at the test project provided as documentation I saw some issues in the test `GrainProbeTests.ProbeWithClassPrefix`. Here is the code of the test for reference:

```C#
public async Task ProbeWithClassPrefix()
{
    Silo.AddProbe<IDevice>("Android", "TestGrains.DeviceAndroidGrain");
    Silo.AddProbe<IDevice>("IOS", "TestGrains.DeviceIosGrain");

    var managerGrain = await this.Silo.CreateGrainAsync<DeviceManagerGrain>(0);
    var iosGrain = await managerGrain.GetDeviceGrain("IOS");
    var androidGrain = await managerGrain.GetDeviceGrain("Android");

    (await iosGrain.GetDeviceType()).Should().Equals("IOS");
    (await iosGrain.GetDeviceType()).Should().Equals("Android");
}
```
The first issue is the duplicated usage of the `iosGrain`. The second issue is the usage of the method `Equals` which is effectively doing nothing since its returned value is not used.

The last two lines of the test should be changed to:
```C#
(await iosGrain.GetDeviceType()).Should().Be("IOS");
(await androidGrain.GetDeviceType()).Should().Be("Android");
```

Unfortunately making this change make the test fail. It is failing on the line `(await iosGrain.GetDeviceType()).Should().Be("IOS");` which was unexpected.

The exception raised is:

```
Expected result to be "IOS", but found <null>.
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Primitives.StringValidator.ValidateAgainstNulls() in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\StringValidator.cs:line 55
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\StringValidator.cs:line 30
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\StringAssertions.cs:line 42
   at Orleans.TestKit.Tests.GrainProbeTests.<ProbeWithClassPrefix>d__11.MoveNext() in D:\OrleansTestKit\test\OrleansTestKit.Tests\Tests\GrainProbeTests.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

I wasn't able to fix that exception as my knowledge of the Orleans test kit is limited.

**Comment by seniorquico** [comment]
Thanks, @Johanny! The call to `Equals` in the assertion lines is definitely a mistake.

However, I'm not entirely sure what was originally intended with those assertions. The calls to `GetDeviceGrain` end up returning mock objects, not real `IAddressable` instances. Additionally, the `GetDeviceType` methods on those mock objects have not been setup. Without being explicitly setup, they return `null` (as you've found).

This test shouldn't be invoking methods on mock objects (because then we'd be testing moq, not showing off the test kit). Additionally, it would be nice to have an example that demonstrates the polymorphic grain call without returning the mock object to the test. I'll work on fixing/improving this test.

**Comment by seniorquico** [comment]
@Johanny, check out the updated tests:

https://github.com/OrleansContrib/OrleansTestKit/blob/3ce7fba5b74a81fca3f91ba05329ce89310fd947/test/OrleansTestKit.Tests/Tests/GrainProbeTests.cs#L145-L173

I hope these make more sense.

**Comment by Johanny** [comment]
Yes the new tests are more insightful on the usage of probes and their possibilities. Thank you for the quick fix 👍
