### ISSUE TITLE
Unit testing streams and unsubscribing

### ISSUE THREAD

**Issue by pawanrao** [OrleansContrib/OrleansTestKit#84]
hey folks,
I'm having a problem testing streams with OrleansTestKit and perhaps someone here could throw some light on why that is happening
My sample code is up here:
https://gist.github.com/pawanrao/6c0c682e490b625a2db7d08098712b3c

The problem I'm facing is that when I try to assert that the stream subscriber for OnNextAsync is called correctly, the unsubscribe seems to happen before the test has executed and I run into the following error:
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)

   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult() in D:\a\1\s\src\NUnitFramework\framework\Internal\TaskAwaitAdapter.cs:line 99
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke) in D:\a\1\s\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 60
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 64
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork() in D:\a\1\s\src\NUnitFramework\framework\Internal\Execution\SimpleWorkItem.cs:line 58
```

I'm a little confused if this is a limitation of OrleansTestKit or if I'm unsubscribing to the stream at the wrong place
Any help would be appreciated!

I posted on the Orleans repo https://github.com/dotnet/orleans/issues/6371 and they suggested posting here since unit testing is involved.

**Comment by seniorquico** [comment]
@pawanrao It appears to be a problem in the TestKit... you unsubscribe, which tries to remove the subscription from a list, while the TestKit is iterating over the list.

[TestStream.cs lines 81-86](https://github.com/OrleansContrib/OrleansTestKit/blob/master/src/OrleansTestKit/Streams/TestStream.cs#L81-L86)

I thought this had been discovered and fixed before. 🤔

All we need to do is copy the list before we iterate and invoke the callbacks. We should add an example like yours as a unit test, too.

**Comment by seniorquico** [comment]
Ah, this same issue had been discovered before with timers:

https://github.com/OrleansContrib/OrleansTestKit/pull/51

We just need to do the same, copy the list before iterating.

**Comment by seniorquico** [comment]
@pawanrao An updated 3.0.1 package has been published to NuGet.
